Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,15 +28,15 @@ jobs:
         run: |
           echo "Contents of dist:"
           ls -la dist/
-          echo "Contents of dist/myPortfolio:"
-          ls -la dist/myPortfolio/ || echo "Folder not found"
+          echo "Contents of dist/my-portfolio:"
+          ls -la dist/my-portfolio/ || echo "Folder not found"
 
       - name: Upload Pages Artifact
         uses: actions/upload-pages-artifact@v3
         with:
           # If the debug shows a 'browser' folder inside dist/myPortfolio, change this to ./dist/myPortfolio/browser
           # If index.html is directly inside dist/myPortfolio, keep it as ./dist/myPortfolio
-          path: ./dist/myPortfolio
+          path: ./dist/my-portfolio
 
   deploy:
     needs: build
